### ISSUE TITLE
Move abspos conversion to the last step and make origin_point a global constant.

### ISSUE THREAD

**Issue by kirilklein** [FGA-DIKU/EHR#16]
Currently, defining the origin_point in the feature creation config requires us to reload the features config at subsequent stages if needed, e.g., during outcome creation and potentially when constructing the fine-tuning index_date.
It would be better to save the origin point in a script so that you can easily import it at any point.

**Comment by mikkelfo** [comment]
I think moving `timestamp->abspos` conversion as late as possible is a high priority and will make the code more intuitive

**Comment by mikkelfo** [comment]
Second point is equal to #27 and fits better
